---
title: "About This Website"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'about.html'))})
output: html_document
---

Below is a list with short descriptions of each page. 

* [**NYC Flights Data**](https://rbolt13.github.io/rsite/nycflightsdata.html) : During class we played around with varous data sets that come pre built into r. Week 6 and 8 we explored the NYC Flight data (from 2013) using dplyr and tidyr, which I found useful to reference when working on different projects. This page also demonstrates various ways to present data using gt and ggplot2.  

* [**Kobe Hot Hands**](https://rbolt13.github.io/rsite/kobehothands.html) : For our first project we took a look at Kobe Bryant's performance with the Los Angeles Lakers in the 2009 NBA finals when playing against the Orlando Magic. This game earned Kobe the title of *Most Valuable Player*, and this study uses data from that game to investigate : Does Kobe Bryant have a Hot Hand? 

* [**Global Fuel Data**](https://rbolt13.github.io/rsite/globalfueldata.html) : For our second project of the term we were given the world power plant data set and tasked to come up with a question we could investigate graphically. Then see if we could reproduce similar graph in base R and ggplot2. 

* [**COVID-19 Data**](https://rbolt13.github.io/rsite/covid.html) : The third and final project for Statistics 363 : Introduction to R, had us looking at data from the COVID-19 pandemic. 

* [**Contact**](https://rbolt13.github.io/rsite/contact.html) : Here you will find my email address, and links to my github and other projects I've done. 

